apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: py-http1p1-helloworld-server-gateway
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: "py-http1p1-helloworld-server.local"

    