apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: MICROSERVICE_NAME_PLACEHOLDER-gateway
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    port: 30080
    protocol: HTTP
    hostname: "MICROSERVICE_NAME_PLACEHOLDER.local"
    
  - name: https
    port: 30443
    protocol: HTTPS
    tls:
      mode: Terminate
      #referencing the secret
      certificateRefs:
      - kind: Secret
        name: http3-tls-cert

  - name: http3-quic
    port: PORT_PLACEHOLDER
    protocol: L4_PROTOCOL_PLACEHOLDER

  

    
