
apiVersion: v1
kind: Service
metadata:
  name: MICROSERVICE_NAME_PLACEHOLDER
spec:
  type: LoadBalancer
  selector:
    app: MICROSERVICE_NAME_PLACEHOLDER
  ports:
  - name: https-tcp
    protocol: TCP
    port: 443      
    targetPort: 443  

    

