apiVersion: v1
kind: Service
metadata:
  name: envoyCBR-HTTPFilter-Service
spec:
  type: ClusterIP
  selector:
    app: envoyCBR-HTTPFilter
  ports:
  - name: grpc
    protocol: TCP
    port: 9002
    targetPort: 9002
    appProtocol: grpc

