apiVersion: apps/v1
kind: Deployment
metadata:
  name: large-sized-data-server--100mb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: large-sized-data-server--100mb
  template:
    metadata:
      labels:
        app: large-sized-data-server--100mb
    spec:
      containers:
      - name: subscriber
        image: davidanthonyvarley/large-sized-data-server--100mb:latest # The image from your Dockerfile [cite: 1]
        imagePullPolicy: IfNotPresent
        env:
        - name: SUB_ID
          value: "subC" 
        volumeMounts:
        - name: testing-data-volume
          mountPath: /mnt/testing-data
          readOnly: true
      volumes:
      - name: testing-data-volume
        persistentVolumeClaim:
          claimName: testing-data-pvc
