apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-service-http3
  namespace: default
spec:
  parentRefs:
    - name: eg   
  rules:
    - backendRefs:
        - name: backend
          protocol: UDP     
          port: 10443          
          weight: 1