apiVersion: v1
kind: Service
metadata:
  name: envoy-gateway-data-plane-lb
  namespace: envoy-gateway-system
  annotations:
    metallb.universe.tf/address-pool: default-ip-addresses-pool
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: proxy
  ports:
  - name: http3
    protocol: UDP
    port: 30003
    targetPort: 30003
    nodePort: 30003
