apiVersion: v1
kind: Service
metadata:
  name: backend-lb
  namespace: default
  annotations:
    metallb.universe.tf/address-pool: metallb-system-ip-addresses-pool
spec:
  type: LoadBalancer
  selector:
    app: backend       # MUST match pod label
  ports:
  - name: http3
    protocol: UDP
    port: 10433          # External port
    targetPort: 10433  # The port the backend container actually listens on