apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-system-ip-addresses-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.59.107-192.168.59.107


---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2
  namespace: metallb-system