apiVersion: v1
kind: Service
metadata:
  name: envoy-gateway-data-plane-lb
  namespace: envoy-gateway-system
  annotations:
    metallb.universe.tf/address-pool: metallb-system-ip-addresses-pool
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: proxy
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
