apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-ip-addresses-pool
  namespace: default
spec:
  addresses:
  - 192.168.1.240-192.168.1.250

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2
  namespace: default