apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-system-ip-addresses-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.2.240-10.0.2.250


---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2
  namespace: metallb-system