apiVersion: apps/v1
kind: Deployment
metadata:
  name: medium-sized-data-server--10mb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medium-sized-data-server--10mb
  template:
    metadata:
      labels:
        app: medium-sized-data-server--10mb
    spec:
      containers:
      - name: subscriber
        image: davidanthonyvarley/medium-sized-data-server--10mb:latest 
        imagePullPolicy: IfNotPresent
        env:
        - name: SUB_ID
          value: "subB" 
        volumeMounts:
        - name: testing-data-volume
          mountPath: /mnt/testing-data
          readOnly: true
      volumes:
      - name: testing-data-volume
        persistentVolumeClaim:
          claimName: testing-data-pvc
