apiVersion: v1
kind: PersistentVolume
metadata:
  name: testing-data-pv
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data/testing_data/