apiVersion: v1
kind: PersistentVolume
metadata:
  name: testing-data-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: ./testing_data/