apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testing-data-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 200Mi
  volumeName: testing-data-pv