apiVersion: v1
kind: Service
metadata:
  name: envoycbr-httpfilter-sidecar-service
spec:
  type: ClusterIP
  selector:
    app: envoycbr-httpfilter-sidecar
  ports:
  - name: grpc
    protocol: TCP
    port: 9002
    targetPort: 9002
    appProtocol: grpc

